# Generated by Django 3.1.3 on 2020-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_auto_20201119_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='random', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('watches', 'Watches')], max_length=20),
        ),
    ]
