# Generated by Django 3.1.3 on 2020-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_imagesearchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Watches', 'Watches'), ('MobileAccessories', 'MobileAccessories'), ('Laptops', 'Laptops'), ('Speakers', 'Speakers'), ('Camera', 'Camera'), ('Footwear', 'Footwear'), ('WinterWear', 'WinterWear'), ('WaterBottle', 'WaterBottle'), ('Bag', 'Bag'), ('Books', 'Books'), ('Cycle', 'Cycle'), ('BankingItems', 'BankingItems'), ('Diaries', 'Diaries'), ('Calculators', 'Calculators'), ('Spectacles', 'Spectacles'), ('Keys', 'Keys'), ('Purse', 'Purse')], max_length=20),
        ),
    ]
